library(snow)
library(raster)
cl <- makeMPIcluster(count=4,names=c("lamapcluster-node001","lamapcluster-node002","lamapcluster-node003","lamapcluster-node004"))
source("../Rlamap/R/jecdf.R")
source("../Rlamap/R/lamap.R")
source("../Rlamap/R/parlamap.R")
source("../Rlamap/R/utils.R")
source("../Rlamap/R/weight.R")
source("../Rlamap/R/parallelscript.R")
